# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x0esensor_service\"P\n\nDadoSensor\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x13\n\x0blocalizacao\x18\x03 \x01(\t\x12\x13\n\x0btemperatura\x18\x04 \x01(\x02\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\"\n\x0bLocalizacao\x12\x13\n\x0blocalizacao\x18\x01 \x01(\t\"F\n\x12ListaDadosSensores\x12\x30\n\x0c\x64\x61\x64os_sensor\x18\x01 \x03(\x0b\x32\x1a.sensor_service.DadoSensor\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyMessage2\xa9\x02\n\rSensorService\x12P\n\x13RegistrarDadoSensor\x12\x1a.sensor_service.DadoSensor\x1a\x1b.sensor_service.StatusReply\"\x00\x12[\n\x1d\x43onsultarDadosSensoresPorData\x12\x14.sensor_service.Data\x1a\".sensor_service.ListaDadosSensores\"\x00\x12i\n$ConsultarDadosSensoresPorLocalizacao\x12\x1b.sensor_service.Localizacao\x1a\".sensor_service.ListaDadosSensores\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _DADOSENSOR._serialized_start=39
  _DADOSENSOR._serialized_end=119
  _DATA._serialized_start=121
  _DATA._serialized_end=141
  _LOCALIZACAO._serialized_start=143
  _LOCALIZACAO._serialized_end=177
  _LISTADADOSSENSORES._serialized_start=179
  _LISTADADOSSENSORES._serialized_end=249
  _STATUSREPLY._serialized_start=251
  _STATUSREPLY._serialized_end=280
  _EMPTYMESSAGE._serialized_start=282
  _EMPTYMESSAGE._serialized_end=296
  _SENSORSERVICE._serialized_start=299
  _SENSORSERVICE._serialized_end=596
# @@protoc_insertion_point(module_scope)
